[phases.setup]
nixPkgs = ["chromium", "python311", "python311Packages.pip"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt", "python -m playwright install chromium"]

[start]
cmd = "python scheduler.py"
